services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
      - ldap
    container_name: frontend_container
    volumes:
      - .:/home/user/workspace:cached
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000
      - LDAP_URL=ldap://ldap:389
    tty: true
    networks:
      - app-network
    command: sleep infinity

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    volumes:
      - .:/home/user/workspace:cached
    ports:
      - "8000:8000"
    networks:
      - app-network
    command: sleep infinity

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap_container
    volumes:
      - ./ldap/database:/var/lib/ldap
      - ./ldap/config:/etc/ldap/slapd.d
    ports:
      - "389:389"
      - "636:636"
    networks:
      - app-network
    environment:
      LDAP_ORGANISATION: "My Company"
      LDAP_DOMAIN: "my-company.com"
      LDAP_ADMIN_PASSWORD: "0000"
    command: sleep infinity

networks:
  app-network:
    driver: bridge