/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kWGS7yARITS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'
import { Rubik } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { LightbulbIcon } from "lucide-react"
import { JSX, SVGProps } from "react"

export function Toppagelayout() {
  return (
    <div className="flex flex-col min-h-screen">
      <section className="bg-gradient-to-r from-primary to-secondary py-20 md:py-32">
        <div className="container mx-auto px-4 md:px-6">
          <div className="max-w-3xl mx-auto text-center">
            <h1 className="text-4xl md:text-6xl font-bold text-primary-foreground mb-4">
              Your AI Assistant for Anything
            </h1>
            <p className="text-lg md:text-xl text-muted-foreground mb-8">
              Get instant answers, analysis, and insights on any topic. Our conversational AI is here to help.
            </p>
            <Link
            href="/login"
            className="inline-flex items-center justify-center h-12 px-6 rounded-md bg-primary text-primary-foreground font-medium transition-transform transform-gpu hover:shadow-lg hover:scale-105 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
            prefetch={false}
            >
            Try it Now
           </Link>



          </div>
        </div>
      </section>
      <section className="py-16 md:py-24">
        <div className="container mx-auto px-4 md:px-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="flex flex-col items-center text-center">
              <LightbulbIcon className="w-12 h-12 text-primary mb-4" />
              <h3 className="text-xl font-semibold mb-2">Instant Insights</h3>
              <p className="text-muted-foreground">
                Get quick, concise answers to your questions on a wide range of topics.
              </p>
            </div>
            <div className="flex flex-col items-center text-center">
              <PencilIcon className="w-12 h-12 text-primary mb-4" />
              <h3 className="text-xl font-semibold mb-2">Helpful Assistance</h3>
              <p className="text-muted-foreground">
                Our AI can assist with writing, analysis, and task planning to boost your productivity.
              </p>
            </div>
            <div className="flex flex-col items-center text-center">
              <PuzzleIcon className="w-12 h-12 text-primary mb-4" />
              <h3 className="text-xl font-semibold mb-2">Endless Capabilities</h3>
              <p className="text-muted-foreground">
                Explore our versatile skills to tackle a wide range of challenges and queries.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="bg-muted py-16 md:py-24">
        <div className="container mx-auto px-4 md:px-6">
          <div className="max-w-3xl mx-auto text-center">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">Latest from the Blog</h2>
            <p className="text-muted-foreground mb-8">
              Stay up-to-date with the latest news, tips, and insights from our team.
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              <Card>
                <CardContent>
                  <h3 className="text-lg font-semibold mb-2">
                    <Link href="#" prefetch={false}>
                      Unlocking the Power of Conversational AI
                    </Link>
                  </h3>
                  <p className="text-muted-foreground line-clamp-3">
                    Discover how our AI assistant can revolutionize the way you work and learn. Explore the latest
                    advancements in natural language processing and how they can benefit your productivity and
                    problem-solving.
                  </p>
                </CardContent>
                <CardFooter>
                  <Link href="#" className="text-primary hover:underline" prefetch={false}>
                    Read More
                  </Link>
                </CardFooter>
              </Card>
              <Card>
                <CardContent>
                  <h3 className="text-lg font-semibold mb-2">
                    <Link href="#" prefetch={false}>
                      5 Ways to Maximize Your AI Assistant
                    </Link>
                  </h3>
                  <p className="text-muted-foreground line-clamp-3">
                    Unlock the full potential of our AI assistant with these practical tips and tricks. Learn how to
                    leverage its capabilities to streamline your workflow, enhance your research, and boost your
                    productivity.
                  </p>
                </CardContent>
                <CardFooter>
                  <Link href="#" className="text-primary hover:underline" prefetch={false}>
                    Read More
                  </Link>
                </CardFooter>
              </Card>
              <Card>
                <CardContent>
                  <h3 className="text-lg font-semibold mb-2">
                    <Link href="#" prefetch={false}>
                      The Future of AI-Powered Assistants
                    </Link>
                  </h3>
                  <p className="text-muted-foreground line-clamp-3">
                    Explore the exciting developments in conversational AI and how they will shape the future of
                    personal and professional productivity. Get a glimpse into the cutting-edge research and innovations
                    that are transforming the way we interact with technology.
                  </p>
                </CardContent>
                <CardFooter>
                  <Link href="#" className="text-primary hover:underline" prefetch={false}>
                    Read More
                  </Link>
                </CardFooter>
              </Card>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}



function PencilIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
      <path d="m15 5 4 4" />
    </svg>
  )
}



function PuzzleIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19.439 7.85c-.049.322.059.648.289.878l1.568 1.568c.47.47.706 1.087.706 1.704s-.235 1.233-.706 1.704l-1.611 1.611a.98.98 0 0 1-.837.276c-.47-.07-.802-.48-.968-.925a2.501 2.501 0 1 0-3.214 3.214c.446.166.855.497.925.968a.979.979 0 0 1-.276.837l-1.61 1.61a2.404 2.404 0 0 1-1.705.707 2.402 2.402 0 0 1-1.704-.706l-1.568-1.568a1.026 1.026 0 0 0-.877-.29c-.493.074-.84.504-1.02.968a2.5 2.5 0 1 1-3.237-3.237c.464-.18.894-.527.967-1.02a1.026 1.026 0 0 0-.289-.877l-1.568-1.568A2.402 2.402 0 0 1 1.998 12c0-.617.236-1.234.706-1.704L4.23 8.77c.24-.24.581-.353.917-.303.515.077.877.528 1.073 1.01a2.5 2.5 0 1 0 3.259-3.259c-.482-.196-.933-.558-1.01-1.073-.05-.336.062-.676.303-.917l1.525-1.525A2.402 2.402 0 0 1 12 1.998c.617 0 1.234.236 1.704.706l1.568 1.568c.23.23.556.338.877.29.493-.074.84-.504 1.02-.968a2.5 2.5 0 1 1 3.237 3.237c-.464.18-.894.527-.967 1.02Z" />
    </svg>
  )
}


function XIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
